---
- hosts: internet
  tasks:
   - name: Configure internet switch
     nclu:
       commands:

         - net add loopback lo ip address 10.0.0.253/32
         - net add bgp autonomous-system 25253
         - net add bgp router-id 10.0.0.253
         - net add loopback lo ip address 172.16.1.1/24
         - net add loopback lo ip address 172.16.2.1/24
         - net add loopback lo ip address 172.16.3.1/24
         - net add loopback lo ip address 172.16.4.1/24
         - net add loopback lo ip address 172.16.5.1/24
         - net add interface swp1 ip address 10.10.10.0/31
         - net add interface swp2 ip address 10.10.10.2/31
         - net add bgp neighbor swp1-2 interface remote-as external
         - net add bgp network 172.16.1.0/24
         - net add bgp network 172.16.2.0/24
         - net add bgp network 172.16.3.0/24
         - net add bgp network 172.16.4.0/24
         - net add bgp network 172.16.5.0/24

       commit: true

- hosts: spine01
  tasks:
   - name: Configure spine01
     nclu:
       commands:

         - net add loopback lo ip address 10.0.0.21/32
         - net add bgp autonomous-system 65020
         - net add bgp bestpath as-path multipath-relax
         - net add bgp router-id 10.0.0.21
         - net add bgp network 10.0.0.21/32
         - net add bgp neighbor swp1-4,swp29-30 interface remote-as external
         - net add bgp evpn neighbor swp1-4,swp29-30 activate
         - net add bgp evpn advertise-all-vni

       commit: true

- hosts: spine02
  tasks:
   - name: Configure spine02
     nclu:
       commands:

         - net add loopback lo ip address 10.0.0.22/32
         - net add bgp autonomous-system 65020
         - net add bgp bestpath as-path multipath-relax
         - net add bgp router-id 10.0.0.22
         - net add bgp network 10.0.0.22/32
         - net add bgp neighbor swp1-4,swp29-30 interface remote-as external
         - net add bgp evpn neighbor swp1-4,swp29-30 activate
         - net add bgp evpn advertise-all-vni

       commit: true

- hosts: exit01
  tasks:
   - name: Configure exit01
     nclu:
       commands:

         - net add loopback lo ip address 10.0.0.41/32
         - net add bgp autonomous-system 65041
         - net add bgp router-id 10.0.0.41
         - net add bgp network 10.0.0.41/32
         - net add bgp neighbor swp51-52 interface remote-as external
         - net add bgp evpn neighbor swp51-52 activate
         - net add bgp evpn advertise-all-vni
         - net add bgp bestpath as-path multipath-relax
         - net add vrf tenant1
         - net add interface swp44 vrf tenant1
         - net add interface swp44 ip address 10.10.10.1/31
         - net add bgp vrf tenant1 autonomous-system 65041
         - net add bgp vrf tenant1 bestpath as-path multipath-relax
         - net add bgp vrf tenant1 neighbor swp44 interface remote-as external
         - net add bgp vrf tenant1 evpn advertise ipv4 unicast
         - net add vlan 4001 vrf tenant1
         - net add vlan 4001 hwaddress 44:38:39:11:00:15
         - net add vxlan vni104001 vxlan id 104001
         - net add vxlan vni104001 bridge access 4001
         - net add vxlan vni104001 bridge learning off
         - net add vxlan vni104001 bridge arp-nd-suppress on
         - net add vxlan vni104001 vxlan local-tunnelip 10.0.0.41
         - net add vrf tenant1 vni 104001

       commit: true

- hosts: exit02
  tasks:
   - name: Configure exit02
     nclu:
       commands:

         - net add loopback lo ip address 10.0.0.42/32
         - net add bgp autonomous-system 65042
         - net add bgp router-id 10.0.0.42
         - net add bgp network 10.0.0.42/32
         - net add bgp neighbor swp51-52 interface remote-as external
         - net add bgp evpn neighbor swp51-52 activate
         - net add bgp evpn advertise-all-vni
         - net add bgp bestpath as-path multipath-relax
         - net add vrf tenant1
         - net add interface swp44 vrf tenant1
         - net add interface swp44 ip address 10.10.10.3/31
         - net add bgp vrf tenant1 autonomous-system 65042
         - net add bgp vrf tenant1 bestpath as-path multipath-relax
         - net add bgp vrf tenant1 neighbor swp44 interface remote-as external
         - net add bgp vrf tenant1 evpn advertise ipv4 unicast
         - net add vlan 4001 vrf tenant1
         - net add vlan 4001 hwaddress 44:38:39:11:00:16
         - net add vxlan vni104001 vxlan id 104001
         - net add vxlan vni104001 bridge access 4001
         - net add vxlan vni104001 bridge learning off
         - net add vxlan vni104001 bridge arp-nd-suppress on
         - net add vxlan vni104001 vxlan local-tunnelip 10.0.0.42
         - net add vrf tenant1 vni 104001

       commit: true

- hosts: leaf01
  tasks:
   - name: Configure leaf01
     nclu:
       commands:

         - net add loopback lo ip address 10.0.0.11/32
         - net add bgp autonomous-system 65011
         - net add bgp router-id 10.0.0.11
         - net add bgp bestpath as-path multipath-relax
         - net add bgp neighbor swp51-52 interface remote-as external
         - net add bgp ipv4 unicast network 10.0.0.11/32
         - net add bgp l2vpn evpn neighbor swp51-52 activate
         - net add bgp l2vpn evpn  advertise-all-vni
         - net add vrf tenant1
         - net add vrf tenant1 vni 104001
         - net add vxlan vni104001 vxlan id 104001
         - net add vxlan vni104001 bridge access 4001
         - net add vlan 4001 hwaddress 44:38:39:11:00:11
         - net add vlan 4001 vrf tenant1
         - net add vxlan vni10100 vxlan id 10100
         - net add vxlan vni10100 bridge access 100
         - net add vxlan vni10100,104001 bridge arp-nd-suppress on
         - net add vxlan vni10100,104001 bridge learning off
         - net add vxlan vni10100,104001 vxlan local-tunnelip 10.0.0.11
         - net add vlan 100 ip address 192.168.100.253/24
         - net add vlan 100 ip address-virtual 44:38:39:aa:aa:aa 192.168.100.254/24
         - net add vlan 100 vlan-id 100
         - net add vlan 100 vlan-raw-device bridge
         - net add vlan 100 vrf tenant1
         - net add interface swp1 bridge access 100

       commit: true

- hosts: leaf02
  tasks:
   - name: Configure leaf02
     nclu:
       commands:

         - net add loopback lo ip address 10.0.0.12/32
         - net add bgp autonomous-system 65012
         - net add bgp router-id 10.0.0.12
         - net add bgp bestpath as-path multipath-relax
         - net add bgp neighbor swp51-52 interface remote-as external
         - net add bgp ipv4 unicast network 10.0.0.12/32
         - net add bgp l2vpn evpn neighbor swp51-52 activate
         - net add bgp l2vpn evpn  advertise-all-vni
         - net add vrf tenant1
         - net add vrf tenant1 vni 104001
         - net add vxlan vni104001 vxlan id 104001
         - net add vxlan vni104001 bridge access 4001
         - net add vlan 4001 hwaddress 44:38:39:11:00:12
         - net add vlan 4001 vrf tenant1
         - net add vxlan vni10100 vxlan id 10100
         - net add vxlan vni10100 bridge access 100
         - net add vxlan vni10100,104001 bridge arp-nd-suppress on
         - net add vxlan vni10100,104001 bridge learning off
         - net add vxlan vni10100,104001 vxlan local-tunnelip 10.0.0.12
         - net add vlan 100 ip address 192.168.100.253/24
         - net add vlan 100 ip address-virtual 44:38:39:aa:aa:aa 192.168.100.254/24
         - net add vlan 100 vlan-id 100
         - net add vlan 100 vlan-raw-device bridge
         - net add vlan 100 vrf tenant1
         - net add interface swp1 bridge access 100

       commit: true
