---
- hosts: internet
  tasks:
   - name: Configure internet switch
     nclu:
       commands:

         -  add loopback lo ip address 10.0.0.253/32
         -  add bgp autonomous-system 25253
         -  add bgp router-id 10.0.0.253
         -  add loopback lo ip address 172.16.1.1/24
         -  add loopback lo ip address 172.16.2.1/24
         -  add loopback lo ip address 172.16.3.1/24
         -  add loopback lo ip address 172.16.4.1/24
         -  add loopback lo ip address 172.16.5.1/24
         -  add interface swp1 ip address 10.10.10.0/31
         -  add interface swp2 ip address 10.10.10.2/31
         -  add bgp neighbor swp1-2 interface remote-as external
         -  add bgp network 172.16.1.0/24
         -  add bgp network 172.16.2.0/24
         -  add bgp network 172.16.3.0/24
         -  add bgp network 172.16.4.0/24
         -  add bgp network 172.16.5.0/24

       commit: true

- hosts: spine01
  tasks:
   - name: Configure spine01
     nclu:
       commands:

         -  add loopback lo ip address 10.0.0.21/32
         -  add bgp autonomous-system 65020
         -  add bgp bestpath as-path multipath-relax
         -  add bgp router-id 10.0.0.21
         -  add bgp network 10.0.0.21/32
         -  add bgp neighbor swp1-4,swp29-30 interface remote-as external
         -  add bgp evpn neighbor swp1-4,swp29-30 activate
         -  add bgp evpn advertise-all-vni

       commit: true

- hosts: spine02
  tasks:
   - name: Configure spine02
     nclu:
       commands:

         -  add loopback lo ip address 10.0.0.22/32
         -  add bgp autonomous-system 65020
         -  add bgp bestpath as-path multipath-relax
         -  add bgp router-id 10.0.0.22
         -  add bgp network 10.0.0.22/32
         -  add bgp neighbor swp1-4,swp29-30 interface remote-as external
         -  add bgp evpn neighbor swp1-4,swp29-30 activate
         -  add bgp evpn advertise-all-vni

       commit: true

- hosts: exit01
  tasks:
   - name: Configure exit01
     nclu:
       commands:

         -  add loopback lo ip address 10.0.0.41/32
         -  add bgp autonomous-system 65041
         -  add bgp router-id 10.0.0.41
         -  add bgp network 10.0.0.41/32
         -  add bgp neighbor swp51-52 interface remote-as external
         -  add bgp evpn neighbor swp51-52 activate
         -  add bgp evpn advertise-all-vni
         -  add bgp bestpath as-path multipath-relax
         -  add vrf tenant1
         -  add interface swp44 vrf tenant1
         -  add interface swp44 ip address 10.10.10.1/31
         -  add bgp vrf tenant1 autonomous-system 65041
         -  add bgp vrf tenant1 bestpath as-path multipath-relax
         -  add bgp vrf tenant1 neighbor swp44 interface remote-as external
         -  add bgp vrf tenant1 evpn advertise ipv4 unicast
         -  add vlan 4001 vrf tenant1
         -  add vlan 4001 hwaddress 44:38:39:11:00:15
         -  add vxlan vni104001 vxlan id 104001
         -  add vxlan vni104001 bridge access 4001
         -  add vxlan vni104001 bridge learning off
         -  add vxlan vni104001 bridge arp-nd-suppress on
         -  add vxlan vni104001 vxlan local-tunnelip 10.0.0.41
         -  add vrf tenant1 vni 104001

       commit: true

- hosts: exit02
  tasks:
   - name: Configure exit02
     nclu:
       commands:

         -  add loopback lo ip address 10.0.0.42/32
         -  add bgp autonomous-system 65042
         -  add bgp router-id 10.0.0.42
         -  add bgp network 10.0.0.42/32
         -  add bgp neighbor swp51-52 interface remote-as external
         -  add bgp evpn neighbor swp51-52 activate
         -  add bgp evpn advertise-all-vni
         -  add bgp bestpath as-path multipath-relax
         -  add vrf tenant1
         -  add interface swp44 vrf tenant1
         -  add interface swp44 ip address 10.10.10.3/31
         -  add bgp vrf tenant1 autonomous-system 65042
         -  add bgp vrf tenant1 bestpath as-path multipath-relax
         -  add bgp vrf tenant1 neighbor swp44 interface remote-as external
         -  add bgp vrf tenant1 evpn advertise ipv4 unicast
         -  add vlan 4001 vrf tenant1
         -  add vlan 4001 hwaddress 44:38:39:11:00:16
         -  add vxlan vni104001 vxlan id 104001
         -  add vxlan vni104001 bridge access 4001
         -  add vxlan vni104001 bridge learning off
         -  add vxlan vni104001 bridge arp-nd-suppress on
         -  add vxlan vni104001 vxlan local-tunnelip 10.0.0.42
         -  add vrf tenant1 vni 104001

       commit: true

- hosts: leaf01
  tasks:
   - name: Configure leaf01
     nclu:
       commands:

         -  add loopback lo ip address 10.0.0.11/32
         -  add bgp autonomous-system 65011
         -  add bgp router-id 10.0.0.11
         -  add bgp bestpath as-path multipath-relax
         -  add bgp neighbor swp51-52 interface remote-as external
         -  add bgp ipv4 unicast network 10.0.0.11/32
         -  add bgp l2vpn evpn neighbor swp51-52 activate
         -  add bgp l2vpn evpn  advertise-all-vni
         -  add vrf tenant1
         -  add vrf tenant1 vni 104001
         -  add vxlan vni104001 vxlan id 104001
         -  add vxlan vni104001 bridge access 4001
         -  add vlan 4001 hwaddress 44:38:39:11:00:11
         -  add vlan 4001 vrf tenant1
         -  add vxlan vni10100 vxlan id 10100
         -  add vxlan vni10100 bridge access 100
         -  add vxlan vni10101 vxlan id 10101
         -  add vxlan vni10101 bridge access 101
         -  add vxlan vni10100,vni10101,104001 bridge arp-nd-suppress on
         -  add vxlan vni10100,vni10101,104001 bridge learning off
         -  add vxlan vni10100,vni10101,104001 vxlan local-tunnelip 10.0.0.11
         -  add vlan 100 ip address 192.168.100.253/24
         -  add vlan 100 ip address-virtual 44:38:39:aa:aa:aa 192.168.100.254/24
         -  add vlan 100 vlan-id 100
         -  add vlan 100 vlan-raw-device bridge
         -  add vlan 100 vrf tenant1
         -  add vlan 101 ip address 192.168.101.253/24
         -  add vlan 101 ip address-virtual 44:38:39:aa:aa:ab 192.168.101.254/24
         -  add vlan 101 vlan-id 101
         -  add vlan 101 vlan-raw-device bridge
         -  add vlan 101 vrf tenant1
         -  add interface swp1 bridge access 100
         -  add interface swp2 bridge access 101

       commit: true

- hosts: leaf02
  tasks:
   - name: Configure leaf02
     nclu:
       commands:

         -  add loopback lo ip address 10.0.0.12/32
         -  add bgp autonomous-system 65012
         -  add bgp router-id 10.0.0.12
         -  add bgp bestpath as-path multipath-relax
         -  add bgp neighbor swp51-52 interface remote-as external
         -  add bgp ipv4 unicast network 10.0.0.12/32
         -  add bgp l2vpn evpn neighbor swp51-52 activate
         -  add bgp l2vpn evpn  advertise-all-vni
         -  add vrf tenant1
         -  add vrf tenant1 vni 104001
         -  add vxlan vni104001 vxlan id 104001
         -  add vxlan vni104001 bridge access 4001
         -  add vlan 4001 hwaddress 44:38:39:11:00:12
         -  add vlan 4001 vrf tenant1
         -  add vxlan vni10100 vxlan id 10100
         -  add vxlan vni10100 bridge access 100
         -  add vxlan vni10101 vxlan id 10101
         -  add vxlan vni10101 bridge access 101
         -  add vxlan vni10100,vni10101,104001 bridge arp-nd-suppress on
         -  add vxlan vni10100,vni10101,104001 bridge learning off
         -  add vxlan vni10100,vni10101,104001 vxlan local-tunnelip 10.0.0.12
         -  add vlan 100 ip address 192.168.100.253/24
         -  add vlan 100 ip address-virtual 44:38:39:aa:aa:aa 192.168.100.254/24
         -  add vlan 100 vlan-id 100
         -  add vlan 100 vlan-raw-device bridge
         -  add vlan 100 vrf tenant1
         -  add vlan 101 ip address 192.168.101.253/24
         -  add vlan 101 ip address-virtual 44:38:39:aa:aa:ab 192.168.101.254/24
         -  add vlan 101 vlan-id 101
         -  add vlan 101 vlan-raw-device bridge
         -  add vlan 101 vrf tenant1
         -  add interface swp2 bridge access 100
         -  add interface swp1 bridge access 101

       commit: true
